In [1]:
import numpy as np
import json
import codecs

In [3]:
# read multiplication table file
infile = [np.asarray(json.loads(line)) for line in open(os.path.abspath(os.pardir) + '\z2_s4_001.json', 'r')]
mixer_index = infile[0]
M = infile[1] #multipliers
T = infile[2] #multiplication table

In [4]:
assert T.shape[0] == T.shape[1] == T.shape[2]
len_T = T.shape[0]
print(len_T)

33


In [5]:
assert M.shape[1] == len_T
len_M = M.shape[0]
print(len_M)

9


In [6]:
# for product of selection pass list ex: brmult_list(T,M,[0,1,2,3])
def brmult_list(T, L, sel = "none"):
    if sel == "none":
        pass
    else:
        L = L[sel,:]
        
    for l in L:
        if all(l == L[0]): # initialize product
            chi = l
        else:
            temp = np.zeros(len(l))
            for i in range(len(l)):
                for j in range(len(l)):
                    temp+= chi[i]*l[j]*T[i][j]
            chi = temp
            #print("-------------------------------------------------------------")
            #print(chi) 
    return chi

In [7]:
key = brmult_list(T, M,)
mixer = np.array([0 for i in range(len(key))])

In [11]:
codecs.encode('message')

b'message'

In [8]:
def set_mixer(mixer, mixer_index, phrase):
    '''ba = bitarray.bitarray()
    ba.frombytes(m.encode('utf-8'))'''
    by = bytearray(phrase,'utf-8')
    for i in range(len(mixer_index)):
        mixer[mixer_index[i]] = by[i]
    return mixer

In [9]:
def encode_msg(m,n):
    '''ba = bitarray.bitarray()
    ba.frombytes(m.encode('utf-8'))'''
    msg1 = bytearray(m,'utf-8')
    
    msg = []
    msg = np.array([0 for i in range(n)])
    for i in range(len(msg1)):
        msg[i]=msg1[i]
    return msg

In [10]:
def brmult(T,msg,key):
    
    coeffs = np.array([0 for i in range(len(key))])
    for k in range(len(key)):
        for i in range(len(key)):
            for j in range(len(msg)):  
                coeffs[k]+=key[i]*msg[j]*T[i][j][k]
    return coeffs

In [14]:
msg = encode_msg("test",len(key)) + set_mixer(mixer,mixer_index,"password")

In [17]:
msg

array([116, 101, 115, 116,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 112,  97, 115, 115, 119])

In [15]:
crypt = brmult(T,msg,key)

In [16]:
crypt

array([   3, -220,  347, -116, -119, -119, -119, -231, -119, -231, -231,
       -231, -231,  238, -231,    0,  119,  119,  119,  119,  119,  231,
        231,  231,  119,  231,  119, -238, -350, -216, -234, -234,  119])

In [18]:
decrypt = brmult(T,crypt,key)

In [19]:
decrypt

array([116, 101, 115, 116,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 112,  97, 115, 115, 119])

1257.434690152932